import React from "react";
import "./Twostepverify.css";
import logo from "../../assets/logokucoin.svg";
import { useNavigate } from "react-router";

const Twostepverify = () => {
    
    const navigate = useNavigate();

  const handlesubmittwo = (event) => {
    event.preventDefault();
    navigate('/important');
  };

  return (
    <div className="container12">
      <img src={logo} alt="" />
      <form onSubmit={handlesubmittwo}>
        <h2>
          2-Step <br /> Verification
        </h2>
        <p className="twopara">
          Enter the 2-step verification generated by your
          <br />
          authenticator app.
        </p>
        <div className="input-field">
          <input type="text" placeholder="Name" required id="name" />
          <input type="number" placeholder="Phone" required id="phone" />
          <button>Verify</button>
        </div>
      </form>
    </div>
  );
};

export default Twostepverify;
